baseurl: "" # the subpath of your site, e.g. /blog
url: "https://studiofluo.fr" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
page_excerpts: true

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

collections:
  portfolio:
    output: true
    permalink: /:collection/:name
  testimonials:
  team:
  clients:
  experiences:
  education:
  services:
  skills:
  process:
  about:

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
  - vendor
