#-------------------------------
# General Site Settings
title: Studio Fluo
logo:
author: Studio Fluo
description: Studio graphique engagé pour mettre de la couleur dans vos idées
email: flora@studiofluo.fr
phone: +33 6 83 65 31 74
address: Villeurbanne
copyright: Copyright &copy; 2020 Design et développement par Studio Fluo
baseline: Des <br> couleurs <br> dans vos idées
menu:
- name: About
  link: /about
- name: Portfolio
  link: /portfolio
- name: Contact
  link: /contact
social:
- icon: ti-facebook
  link: "https://www.facebook.com/studiofluodesign/"
- icon: ti-instagram
  link: "https://www.instagram.com/studiofluodesign/"

# Titres de sections
testimonial: Témoignages
team: Partenaires
clients: Ils me font confiance
contact: Contactez-moi
education: Mes formations
experiences: Mon historique
process: Vos visuels en 3 étapes
services: Mes services
skills: Mes compétences