title: Studio Fluo
logo: /assets/images/uploads/asset-10-0.5x.png
favicon: /assets/images/favicon.png
author: Studio Fluo
description: Studio graphique engagé pour mettre de la couleur dans vos idées
email: flora@studiofluo.fr
phone: +33 6 83 65 31 74
address: Rhône-Alpes, entre Lyon & Pierrelatte
copyright: Copyright &copy; 2020 Design et développement par Studio Fluo
menu:
  - name: Accueil
    link: /
  - name: Qui suis-je ?
    link: /about
  - name: Portfolio
    link: /portfolio
baseline: Des <br> couleurs <br> dans vos idées
social:
  - icon: ico-facebook
    link: https://www.facebook.com/studiofluodesign/
    handle: studiofluodesign
  - icon: ico-instagram
    link: https://www.instagram.com/studiofluodesign/
    handle: studiofluodesign
  - icon: ico-linkedin
    link: https://www.linkedin.com/company/studiofluodesign
    handle: studiofluodesign
testimonial: Témoignages
portfolio: Mes réalisations
team: Partenaires
clients: Ils me font confiance
contact: Contactez-moi
education: Mes formations
experiences: Mon historique
process: Vos visuels en 3 étapes
services: Mes services
skills: Mes compétences
