title: Studio Fluo
logo: /assets/images/uploads/logo-white.svg
author: Studio Fluo
description: Studio graphique engagé pour mettre de la couleur dans vos idées !
  Un logo, des illustrations personnalisée ou bien une affiche ? Vous êtes au
  bon endroit !
email: flora@studiofluo.fr
address: Rhône-Alpes, entre Lyon & Pierrelatte
copyright: Copyright &copy; 2020-2021. Design et développement par Studio Fluo
menu:
  - name: Accueil
    link: /
  - name: Services
    link: /services
  - name: Réalisations
    link: /portfolio
  - name: Qui suis-je ?
    link: /about
  - name: Contact
    link: /contact
baseline: Des <br> couleurs <br> dans vos idées
testimonial: Témoignages
team: Partenaires
contact: Contactez-moi
services: Mes services
skills: Mes compétences
portfolio: Mes dernières réalisations
clients: Ils me font confiance
education: Mes formations
experiences: Mon historique
intro: >
  ## Bonjour et bienvenue dans votre espace créatif !     


  {: .lead}

  Ici, on <mark>design</mark>, on <mark>dessine</mark> et on <mark>décide</mark>. Vous avez besoin d'une nouvelle charte ? Je m'en occupe ! Des illustrations pour donner vie à vos documents ? C'est possible ! Créer un faire-part unique ? Vous êtes au bon endroit !
social:
  - icon: ico-facebook
    link: https://www.facebook.com/studiofluodesign/
    handle: studiofluodesign
  - icon: ico-instagram
    link: https://www.instagram.com/studiofluodesign/
    handle: studiofluodesign
  - icon: ico-linkedin
    link: https://www.linkedin.com/company/studiofluodesign
    handle: studiofluodesign
about: Qui suis-je ?
favicon: /assets/images/favicon.png
phone: +33 6 83 65 31 74
process: Vos visuels en 3 étapes
