#-------------------------------
# General Site Settings
title: Studio Fluo
logo:
author: Studio Fluo
description: Studio graphique engagé pour mettre de la couleur dans vos idées
email: flora@studiofluo.fr
phone: +33 6 83 65 31 74
address: Villeurbanne
copyright: Copyright &copy; 2020 Design et développement par Studio Fluo
menu:
- name: About
  link: /about
- name: Portfolio
  link: /portfolio
- name: Contact
  link: /contact
# Hero Section
hero:
  hero-title: Des <br> couleurs <br> dans vos idées
social:
- icon: ti-facebook
  link: "https://www.facebook.com/studiofluodesign/"
- icon: ti-instagram
  link: "https://www.instagram.com/studiofluodesign/"
