#-------------------------------
# General Site Settings

title: Studio Fluo
logo: 
author: Studio Fluo
description: this is meta description
email: flora@richardet.fr
phone: +33 6 83 65 31 74
address: Villeurbanne
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Des <br> couleurs <br> dans vos idées

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Passionnée de lumière. Le nom de mon studio vient de mon expérience dans la fluorescence ! Scientifique de formation j'ai changé de voie pour donner du sens à mon travail et exprimer ma créativité.
blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Les racines"
    icon : "assets/images/icons/plan.png"
    content : "Je suis à l'écoute pour comprendre vos besoins et cerner votre identité."
    
  - title : "La graine"
    icon : "assets/images/icons/design.png"
    content : "Je vous propose des pistes créatives inventives."
    
  - title : "L'écolosion"
    icon : "assets/images/icons/print.png"
    content : "Je vous accompagne jusqu'au lancement en faisant appel aux bons partenaires."


# My Team Section
team:
  - title : "Flavia Ribes"
    image : "assets/images/team/member-1.png"
    designation : "Facilitatrice"
    

#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Suite Adobe, color: '#fdb157', value: '90%'}
- {name: Empathie, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '90%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Formation
education:
- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
- {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
- {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}
#- {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
#- {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
#- {name: TOSA Illustrator, date: '2020', organization: 'Certification'}
#- {name: Optique, date: '2011', organization: 'Diplme d'Ingnieur'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: UI Design,
    icon: ti-palette,
    description: 'Logo, Chartre graphique, Refonte d'identit, Carte de Visite',
    active: # Add true to select section
  }
- {
    name: UX Design,
    icon: ti-vector,
    description: 'Affiche, Flyer, Faire-Part, Brochure',
    active: true # Add true to select section
  }
- {
    name: Interactin Design,
    icon: ti-panel,
    description: 'Badge, Sticker, Design textile',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "Identité Graphique",
    type : "design"
  }
- {
    title : "Illustration",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
    
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Robin Gueguen"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "<strong> C'est vraiment nickel.</strong> Tu vas devenir ma graphiste officielle :)"
    
  - name: "Flavia Ribes"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "[09:23, 08/10/2020] Merci merci 🙏 <strong> Vraiment c'est tout ce que j'attendai </strong>"
    
 
#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: flora@richardet.fr
