backend:
  name: github
  repo: JbIPS/studiofluo.fr
  branch: master # Branch to update (optional; defaults to master)
  site_domain: studiofluo.fr #fervent-booth-0686d7.netlify.com

media_folder: "assets/images/uploads"
collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio" # Used in the UI
    folder: "_portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown"}